spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assurance_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false # <-- Ajoute ça