server:
  error:
    include-message: always

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/assurance_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    open-in-view: false

jwt:
  secret: "U3VwZXJTZWNyZXRLZXlQb3VyTGVTdGFnZURhc3N1cmFuY2UyMDI0IQ=="